import {
  Course,
  Cohort,
  ProjectTrack,
  StudentProject,
  Portfolio,
  Organization,
  User
} from './types';

export const mockOrganization: Organization = {
  id: 'org-1',
  name: 'Acme Academy',
  slug: 'acme-academy',
  plan: 'free',
  activeSeats: 5,
  maxSeats: 5,
};

export const mockInstructorUser: User = {
  id: 'usr-nicole',
  name: 'Dr. Nicole Wang',
  email: 'n.wang@acme.edu',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
  role: 'instructor',
};

export const mockStudentUser: User = {
  id: 'usr-maya',
  name: 'Maya Chen',
  email: 'm.chen@student.edu',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
  role: 'student',
};

export const mockCourse: Course = {
  id: 'course-pm101',
  title: 'Product Management Foundations',
  description: 'Master core product strategy, user discovery, prototyping, and iterative validation through practical real-world execution.',
  organizationId: 'org-1',
  modules: [
    {
      id: 'mod-1',
      number: 1,
      title: 'Understanding User Problems',
      description: 'Learn qualitative user research techniques, interview synthesis, and persona empathy mapping.',
      items: [
        { id: 'i-101', title: 'Video: Conducting Non-Biased User Interviews', type: 'video', duration: '14 min', completed: true },
        { id: 'i-102', title: 'Reading: The Mom Test Principles', type: 'reading', duration: '10 min', completed: true },
        { id: 'i-103', title: 'Quiz: User Interview Best Practices', type: 'quiz', duration: '10 questions', completed: true },
      ],
    },
    {
      id: 'mod-2',
      number: 2,
      title: 'Market Research',
      description: 'Analyze total addressable market, competitive positioning, and unmet user needs.',
      items: [
        { id: 'i-201', title: 'Video: Competitive Matrix Analysis', type: 'video', duration: '18 min', completed: true },
        { id: 'i-202', title: 'Reading: Industry Benchmark Frameworks', type: 'reading', duration: '12 min', completed: true },
        { id: 'i-203', title: 'Quiz: Market Sizing & Signals', type: 'quiz', duration: '8 questions', completed: true },
      ],
    },
    {
      id: 'mod-3',
      number: 3,
      title: 'Value Proposition',
      description: 'Formulate testable hypotheses, value propositions, and positioning frameworks.',
      items: [
        { id: 'i-301', title: 'Video: Designing Value Proposition Canvas', type: 'video', duration: '16 min', completed: false },
        { id: 'i-302', title: 'Reading: Pain Relievers vs Gain Creators', type: 'reading', duration: '8 min', completed: false },
        { id: 'i-303', title: 'Quiz: Value Proposition Sharpness', type: 'quiz', duration: '10 questions', completed: false },
      ],
    },
    {
      id: 'mod-4',
      number: 4,
      title: 'Prototype Design',
      description: 'Build low-fidelity interactive wires and clickable user flows for immediate feedback.',
      items: [
        { id: 'i-401', title: 'Video: Low-Fidelity Wireframing Basics', type: 'video', duration: '22 min', completed: false },
        { id: 'i-402', title: 'Reading: Figma Prototyping Essentials', type: 'reading', duration: '15 min', completed: false },
        { id: 'i-403', title: 'Quiz: UX Usability Standards', type: 'quiz', duration: '5 questions', completed: false },
      ],
    },
    {
      id: 'mod-5',
      number: 5,
      title: 'User Testing',
      description: 'Facilitate moderated user testing sessions and extract actionable iteration insights.',
      items: [
        { id: 'i-501', title: 'Video: Measuring Task Completion & Friction', type: 'video', duration: '20 min', completed: false },
        { id: 'i-502', title: 'Reading: Usability Feedback Matrices', type: 'reading', duration: '10 min', completed: false },
        { id: 'i-503', title: 'Quiz: Test Protocols & Analysis', type: 'quiz', duration: '10 questions', completed: false },
      ],
    },
    {
      id: 'mod-6',
      number: 6,
      title: 'Product Storytelling',
      description: 'Package user research, prototypes, and validation metrics into executive case studies.',
      items: [
        { id: 'i-601', title: 'Video: Pitching Product Decisions to Stakeholders', type: 'video', duration: '15 min', completed: false },
        { id: 'i-602', title: 'Reading: Case Study Portfolio Structures', type: 'reading', duration: '12 min', completed: false },
        { id: 'i-603', title: 'Quiz: Storytelling & Metric Presentation', type: 'quiz', duration: '8 questions', completed: false },
      ],
    },
  ],
};

export const mockCohort: Cohort = {
  id: 'cohort-fall2026',
  courseId: 'course-pm101',
  name: 'Fall 2026 Cohort',
  season: 'Fall 2026',
  totalStudents: 18,
  avgCompletionRate: 62,
  studentsNeedingAttention: 4,
};

export const mockProjectTrack: ProjectTrack = {
  id: 'track-val-101',
  courseId: 'course-pm101',
  title: 'Validate a Real Product Opportunity',
  goal: 'Validate a product idea with real users',
  level: 'Intermediate',
  industry: 'Open choice',
  format: 'Individual',
  durationWeeks: 4,
  weeklyEffortHours: '3–4 hours',
  published: true,
  objective: 'Students identify a real user problem, interview potential users, develop a lightweight prototype, and test whether the proposed solution addresses the problem.',
  milestones: [
    {
      id: 'm-1',
      weekNumber: 1,
      title: 'Week 1 — Problem Discovery',
      tasks: [
        'Select a target user group',
        'Conduct three user interviews',
        'Submit interview notes',
        'Identify recurring pain points',
      ],
      deliverables: ['3 Raw User Interview Transcripts/Notes', 'Empathy Synthesis Sheet'],
    },
    {
      id: 'm-2',
      weekNumber: 2,
      title: 'Week 2 — Opportunity Definition',
      tasks: [
        'Define the primary problem statement',
        'Create a value proposition canvas',
        'Submit an evidence-based problem statement',
      ],
      deliverables: ['Evidence-Based Problem Statement Document', 'Value Proposition Graphic'],
    },
    {
      id: 'm-3',
      weekNumber: 3,
      title: 'Week 3 — Prototype and Testing',
      tasks: [
        'Create a lightweight prototype',
        'Test it with two target users',
        'Upload feedback and observations',
      ],
      deliverables: ['Figma Prototype Link / Screenshots', '2 User Testing Session Recordings / Notes'],
    },
    {
      id: 'm-4',
      weekNumber: 4,
      title: 'Week 4 — Reflection and Portfolio',
      tasks: [
        'Document what changed between initial idea and tested prototype',
        'Explain evidence and key decision trade-offs',
        'Generate a final public portfolio page',
      ],
      deliverables: ['Final Case Study Reflection', 'Published Verified BlueQ Portfolio Page'],
    },
  ],
  requiredEvidence: [
    'Interview notes',
    'Problem statement',
    'Prototype screenshots or link',
    'User feedback',
    'Final reflection',
  ],
  finalDeliverable: 'A public project case-study page reviewed and verified by the instructor.',
  rubric: [
    { criteria: 'Quality of user evidence', description: 'Grounded in authentic user quotes and observational feedback from at least 3 subjects.' },
    { criteria: 'Problem clarity', description: 'Clearly framed problem statement with supporting metrics or root-cause synthesis.' },
    { criteria: 'Iteration based on feedback', description: 'Explicit evidence showing how prototype evolved after user testing sessions.' },
    { criteria: 'Reflection quality', description: 'Thoughtful analysis of assumptions that were invalidated during research.' },
    { criteria: 'Communication of outcomes', description: 'Clean, professional structure suitable for external hiring managers and stakeholders.' },
  ],
};

export const initialStudentProjects: StudentProject[] = [
  {
    id: 'sp-maya',
    studentId: 'usr-maya',
    studentName: 'Maya Chen',
    studentEmail: 'm.chen@student.edu',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    projectTrackId: 'track-val-101',
    currentWeek: 2,
    overallProgress: 45,
    nextDeadline: 'Opportunity Definition (Due Oct 18)',
    instructorName: 'Dr. Nicole Wang',
    riskStatus: 'On track',
    reviewStatus: 'Needs Review',
    completedTaskIds: [
      'Select a target user group',
      'Conduct three user interviews',
      'Submit interview notes',
      'Identify recurring pain points',
      'Define the primary problem statement',
    ],
    reflectionText: 'During my interviews with freelance remote designers, I initially hypothesized that client scheduling was their biggest headache. However, 3 out of 3 interviewees spent 80% of their rant complaining about invoice tracking and delayed payments. I pivot-focused my problem statement around payment transparency.',
    evidence: [
      {
        id: 'ev-1',
        studentProjectId: 'sp-maya',
        milestoneId: 'm-1',
        title: 'User Interview Notes - 3 Remote Freelancers',
        type: 'text',
        content: `Subject A (UI Designer, 4 yrs exp): "I spend 3 hours every Friday chasing $500 invoices."
Subject B (UX Researcher, 2 yrs exp): "Clients pretend they didn't receive PDFs. I need real-time read receipts on invoices."
Subject C (Brand Designer, 6 yrs exp): "Milestone payments are always late because approval triggers aren't clear."`,
        submittedAt: '2 days ago',
      },
      {
        id: 'ev-2',
        studentProjectId: 'sp-maya',
        milestoneId: 'm-2',
        title: 'Evidence-Based Problem Statement & Value Prop',
        type: 'link',
        content: 'https://figma.com/file/maya-chen-freelance-payment-problem-statement',
        submittedAt: 'Yesterday',
        fileName: 'Figma Canvas - Payment Transparency Map',
      },
      {
        id: 'ev-3',
        studentProjectId: 'sp-maya',
        milestoneId: 'm-3',
        title: 'Interactive Low-Fi Prototype (Figma)',
        type: 'link',
        content: 'https://figma.com/proto/maya-paytrack-prototype-v1',
        submittedAt: 'Today at 09:30 AM',
        fileName: 'PayTrack Prototype Link',
      }
    ],
    reviews: [
      {
        id: 'rev-1',
        studentProjectId: 'sp-maya',
        milestoneId: 'm-1',
        instructorId: 'usr-nicole',
        status: 'approved',
        feedback: 'Great depth on the interview transcripts, Maya! You extracted verbatim quotes that clearly highlight friction around payment triggers rather than calendar scheduling.',
        reviewedAt: '3 days ago',
      },
    ],
    agentGuidanceLogs: [
      {
        sender: 'agent',
        text: 'Your interviews describe several frustrations, but the evidence is still broad. Which problem appeared consistently across at least two interviews?',
        timestamp: '10:15 AM',
      },
      {
        sender: 'student',
        text: 'Delayed invoice payments and missing read receipts came up in all 3 interviews.',
        timestamp: '10:18 AM',
      },
      {
        sender: 'agent',
        text: 'Excellent insight. Make sure to ground your Week 2 Problem Statement on those verbatim quotes before submitting for Dr. Nicole Wang’s review.',
        timestamp: '10:19 AM',
      },
    ],
  },
  {
    id: 'sp-ethan',
    studentId: 'usr-ethan',
    studentName: 'Ethan Park',
    studentEmail: 'e.park@student.edu',
    studentAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    projectTrackId: 'track-val-101',
    currentWeek: 2,
    overallProgress: 25,
    nextDeadline: 'Opportunity Definition',
    instructorName: 'Dr. Nicole Wang',
    riskStatus: 'Missing evidence',
    reviewStatus: 'Pending Submission',
    completedTaskIds: ['Select a target user group'],
    reflectionText: 'I tried reaching out to campus store managers, but only got 1 response so far.',
    evidence: [
      {
        id: 'ev-ethan-1',
        studentProjectId: 'sp-ethan',
        milestoneId: 'm-1',
        title: 'Preliminary Survey Link (Only 1 response)',
        type: 'link',
        content: 'https://forms.google.com/ethan-store-survey',
        submittedAt: '4 days ago',
      },
    ],
    reviews: [],
    agentGuidanceLogs: [
      {
        sender: 'agent',
        text: 'You need at least 3 qualitative user interview notes to complete Milestone 1. Consider conducting short 5-minute intercept interviews at the student center.',
        timestamp: 'Yesterday',
      },
    ],
  },
  {
    id: 'sp-sofia',
    studentId: 'usr-sofia',
    studentName: 'Sofia Martinez',
    studentEmail: 's.martinez@student.edu',
    studentAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    projectTrackId: 'track-val-101',
    currentWeek: 3,
    overallProgress: 70,
    nextDeadline: 'Prototype Testing Feedback',
    instructorName: 'Dr. Nicole Wang',
    riskStatus: 'Waiting review',
    reviewStatus: 'Needs Review',
    completedTaskIds: [
      'Select a target user group',
      'Conduct three user interviews',
      'Submit interview notes',
      'Identify recurring pain points',
      'Define the primary problem statement',
      'Create a value proposition canvas',
      'Create a lightweight prototype',
    ],
    reflectionText: 'Built a Notion template prototype for community event managers. Tested with 2 local organizers.',
    evidence: [
      {
        id: 'ev-sofia-1',
        studentProjectId: 'sp-sofia',
        milestoneId: 'm-3',
        title: 'Notion Event Planner Prototype & User Session Audio Notes',
        type: 'text',
        content: 'Notion prototype tested with 2 local non-profit event leads. Both completed the setup in under 4 minutes.',
        submittedAt: '5 hours ago',
      },
    ],
    reviews: [],
    agentGuidanceLogs: [
      {
        sender: 'agent',
        text: 'All 3 milestones have complete evidence. Ready for Dr. Nicole Wang’s approval.',
        timestamp: '5 hours ago',
      },
    ],
  },
  {
    id: 'sp-liam',
    studentId: 'usr-liam',
    studentName: 'Liam Johnson',
    studentEmail: 'l.johnson@student.edu',
    studentAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    projectTrackId: 'track-val-101',
    currentWeek: 2,
    overallProgress: 30,
    nextDeadline: 'Opportunity Definition',
    instructorName: 'Dr. Nicole Wang',
    riskStatus: 'Scope alert',
    reviewStatus: 'Revision Requested',
    completedTaskIds: ['Select a target user group', 'Conduct three user interviews'],
    reflectionText: 'I am trying to solve global supply chain transparency, AI crop tracking, and freight billing all in one app.',
    evidence: [
      {
        id: 'ev-liam-1',
        studentProjectId: 'sp-liam',
        milestoneId: 'm-1',
        title: 'Global Supply Chain Research PDF (50 pages)',
        type: 'text',
        content: 'Broad overview of ocean freight, customs brokerage, and local delivery logistics.',
        submittedAt: '3 days ago',
      },
    ],
    reviews: [
      {
        id: 'rev-liam-1',
        studentProjectId: 'sp-liam',
        milestoneId: 'm-1',
        instructorId: 'usr-nicole',
        status: 'revision_requested',
        feedback: 'Liam, this topic is too vast for a 4-week project track. Please narrow down your target user to a single role (e.g. local organic farm manager) and re-submit your focus.',
        reviewedAt: '2 days ago',
      },
    ],
    agentGuidanceLogs: [
      {
        sender: 'agent',
        text: 'Your project scope spans 3 different industries. Narrow down to 1 specific user sub-group to pass Week 2 review.',
        timestamp: '2 days ago',
      },
    ],
  },
  {
    id: 'sp-alex',
    studentId: 'usr-alex',
    studentName: 'Alex Rivera',
    studentEmail: 'a.rivera@student.edu',
    studentAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=200',
    projectTrackId: 'track-val-101',
    currentWeek: 4,
    overallProgress: 90,
    nextDeadline: 'Final Portfolio Submission',
    instructorName: 'Dr. Nicole Wang',
    riskStatus: 'On track',
    reviewStatus: 'Approved',
    completedTaskIds: [
      'Select a target user group',
      'Conduct three user interviews',
      'Submit interview notes',
      'Identify recurring pain points',
      'Define the primary problem statement',
      'Create a value proposition canvas',
      'Create a lightweight prototype',
      'Test it with two target users',
      'Upload feedback and observations',
    ],
    reflectionText: 'Iterated from a web dashboard to a Slack bot based on user testing. Great learning experience.',
    evidence: [],
    reviews: [],
    agentGuidanceLogs: [],
  },
];

export const mockMayaPortfolio: Portfolio = {
  id: 'port-maya-1',
  studentProjectId: 'sp-maya',
  studentName: 'Maya Chen',
  studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
  projectTitle: 'PayTrack: Invoice Transparency for Freelance Creators',
  verified: true,
  verifiedBy: 'Dr. Nicole Wang (Instructor, Product Management Foundations)',
  verifiedAt: 'Fall 2026 Cohort',
  projectChallenge: 'Freelance creative professionals waste over 10 hours per month chasing unpaid client invoices and struggling with vague payment terms. The goal was to validate whether real-time invoice milestone notifications could eliminate client-freelancer friction.',
  userResearch: {
    summary: 'Conducted 3 in-depth qualitative interviews with active freelance designers and UX researchers managing $2k-$10k monthly client billings.',
    keyQuotes: [
      '"I spend 3 hours every Friday chasing $500 invoices."',
      '"Clients pretend they didn’t receive PDFs. I need real-time read receipts on invoices."',
      '"Milestone payments are always late because approval triggers aren’t clear."',
    ],
    interviewCount: 3,
  },
  keyInsights: [
    'Pain shifts from scheduling to cash flow: Designers cared far more about invoice delivery transparency than calendar bookings.',
    'Proof of Delivery is critical: Freelancers need automated read-receipts and payment milestone unlocks.',
    'Low-friction onboarding: Clients refuse to create a new account just to view an invoice PDF.',
  ],
  prototype: {
    description: 'Designed a lightweight pay-link web interface allowing freelancers to issue transparent milestone invoices with instant SMS/Email view notifications.',
    url: 'https://figma.com/proto/maya-paytrack-prototype-v1',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
  },
  testingAndIteration: 'Tested prototype with 2 target users. Key iteration: Replaced mandatory login with a magic secure link access, reducing client invoice view friction from 90 seconds to 3 seconds.',
  finalOutcome: 'Validated core value proposition with 100% test user completion rate. Received 5 star satisfaction score on prototype clarity.',
  reflection: 'This project taught me the power of rigorous user discovery. By grounding my assumptions in raw interview quotes rather than guessing, I pivoted early from a generic booking tool to a targeted payment transparency product.',
  publishedUrl: 'https://blueq.edu/portfolios/maya-chen-paytrack-2026',
};
